apiVersion: v1
secrets:
  # Core application secrets
  - kind: Secret
    metadata:
      name: art-knowledge-graph-secrets
      namespace: default
      labels:
        app: art-knowledge-graph
        environment: production
        component: backend
        managed-by: terraform
      annotations:
        description: Core secrets for Art Knowledge Graph backend services
        rotation-schedule: 90d
        last-rotated: 2023-01-01T00:00:00Z
    type: Opaque

  # Backend core secrets
  - kind: Secret
    metadata:
      name: backend-secrets
      namespace: default
      labels:
        app: art-knowledge-graph
        component: core
        environment: production
    data:
      SECRET_KEY: ${BASE64_ENCODED_JWT_SECRET}
      JWT_ALGORITHM: SFMyNTY=  # HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: MzA=  # 30
      ENCRYPTION_KEY: ${BASE64_ENCODED_ENCRYPTION_KEY}
      SECURE_HEADERS_CONFIG: ${BASE64_ENCODED_SECURITY_HEADERS}
      APP_SECRET_KEY: ${BASE64_ENCODED_APP_SECRET}
      DEBUG_MODE: ZmFsc2U=  # false

  # Database connection secrets
  - kind: Secret
    metadata:
      name: database-secrets
      namespace: default
      labels:
        app: art-knowledge-graph
        component: database
        environment: production
    data:
      # Neo4j Configuration
      NEO4J_URI: ${BASE64_ENCODED_NEO4J_URI}
      NEO4J_USER: ${BASE64_ENCODED_NEO4J_USER}
      NEO4J_PASSWORD: ${BASE64_ENCODED_NEO4J_PASSWORD}
      NEO4J_AUTH_TOKEN: ${BASE64_ENCODED_NEO4J_AUTH_TOKEN}
      
      # PostgreSQL Configuration
      POSTGRES_URI: ${BASE64_ENCODED_POSTGRES_URI}
      POSTGRES_USER: ${BASE64_ENCODED_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BASE64_ENCODED_POSTGRES_PASSWORD}
      POSTGRES_SSL_MODE: dmVyaWZ5LWZ1bGw=  # verify-full
      
      # Redis Configuration
      REDIS_URI: ${BASE64_ENCODED_REDIS_URI}
      REDIS_PASSWORD: ${BASE64_ENCODED_REDIS_PASSWORD}
      REDIS_SSL: dHJ1ZQ==  # true

  # External API secrets
  - kind: Secret
    metadata:
      name: api-secrets
      namespace: default
      labels:
        app: art-knowledge-graph
        component: external-apis
        environment: production
    data:
      # Getty API Configuration
      GETTY_API_KEY: ${BASE64_ENCODED_GETTY_API_KEY}
      GETTY_API_SECRET: ${BASE64_ENCODED_GETTY_API_SECRET}
      GETTY_API_ENDPOINT: ${BASE64_ENCODED_GETTY_ENDPOINT}
      
      # Google Arts & Culture API Configuration
      GOOGLE_ARTS_API_KEY: ${BASE64_ENCODED_GOOGLE_ARTS_KEY}
      GOOGLE_ARTS_PROJECT_ID: ${BASE64_ENCODED_GOOGLE_ARTS_PROJECT}
      
      # AWS Configuration
      AWS_ACCESS_KEY_ID: ${BASE64_ENCODED_AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${BASE64_ENCODED_AWS_SECRET_KEY}
      AWS_REGION: dXMtZWFzdC0x  # us-east-1
      AWS_S3_BUCKET: ${BASE64_ENCODED_S3_BUCKET}