platform :ios, '14.0'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

target 'ArtKnowledgeGraph' do
  pod 'D3Swift', '~> 7.0.0'
  pod 'Alamofire', '~> 5.8.0'
  pod 'KeychainAccess', '~> 4.2.0'
  pod 'Firebase/Analytics', '~> 10.0.0'
  pod 'SDWebImage', '~> 5.18.0'
  pod 'SwiftyJSON', '~> 5.0.0'

  target 'ArtKnowledgeGraphTests' do
    inherit! :search_paths
    pod 'Quick', '~> 7.0.0'
    pod 'Nimble', '~> 12.0.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['ENABLE_BITCODE'] = 'YES'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '3'
      config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end