# Tempo Configuration v2.1+
# Distributed tracing backend optimized for art graph operations

# Global auth settings
auth_enabled: false

# Server configuration with optimized timeouts for graph operations
server:
  http_listen_port: 3200
  grpc_listen_port: 9095
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s

# Distributor configuration for multi-protocol trace ingestion
distributor:
  receivers:
    jaeger:
      protocols:
        grpc:
          endpoint: "0.0.0.0:14250"
        thrift_http:
          endpoint: "0.0.0.0:14268"
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

# Ingester configuration optimized for art graph operations
ingester:
  max_block_duration: 5m
  complete_block_timeout: 30m
  flush_check_period: 30s
  trace_retention: 336h  # 14 days retention
  lifecycler:
    ring:
      replication_factor: 3
      kvstore:
        store: memberlist

# Compactor settings for efficient trace storage
compactor:
  compaction:
    block_retention: 336h  # 14 days retention
    compacted_block_retention: 1h
    compaction_window: 1h
    max_compaction_objects: 1000000
  ring:
    kvstore:
      store: memberlist

# Storage configuration for AWS S3
storage:
  trace:
    backend: s3
    s3:
      bucket: art-knowledge-graph-traces-${ENV}
      region: ${AWS_REGION}
      access_key: ${AWS_ACCESS_KEY}
      secret_key: ${AWS_SECRET_KEY}
      insecure: false
      # Optimize for parallel processing
      pool:
        max_workers: 100
        queue_depth: 10000
    blocklist_poll: 5m
    cache: memcached
    memcached:
      consistent_hash: true
      host: memcached
      service: memcached-client
      timeout: 200ms

# Query frontend settings
query_frontend:
  search:
    max_duration: 1h
  trace_by_id:
    max_duration: 1h

# Tenant-specific overrides for art graph operations
overrides:
  max_bytes_per_trace: 50000000  # 50MB max trace size
  max_search_duration: 1h
  max_bytes_per_tag_values_query: 5242880  # 5MB
  ingestion_rate_limit_bytes: 15728640  # 15MB/sec
  ingestion_burst_size_bytes: 20971520  # 20MB

# Memberlist configuration for cluster coordination
memberlist:
  abort_if_cluster_join_fails: false
  join_members:
    - tempo-gossip-ring
  max_join_backoff: 1m
  max_join_retries: 10
  min_join_backoff: 1s

# Metrics configuration
usage_report:
  reporting_enabled: false

# OpenTelemetry configuration
opencensus:
  sampler:
    type: probabilistic
    sampling_fraction: 1.0  # Sample all traces for art graph operations

# Logging configuration
logger:
  level: info
  format: logfmt

# Lifecycle hooks
lifecycle:
  ring:
    replication_factor: 3
    kvstore:
      store: memberlist

# Runtime configuration
runtime_config:
  file: /conf/tempo-runtime.yaml