name: Web Build

on:
  push:
    paths:
      - 'src/web/**'
  pull_request:
    paths:
      - 'src/web/**'

env:
  NODE_VERSION: '18.x'
  WORKING_DIRECTORY: 'src/web'
  COVERAGE_THRESHOLD: '80'
  CACHE_KEY_PREFIX: 'npm-cache-v1'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.WORKING_DIRECTORY }}/node_modules
            ~/.npm
          key: ${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.CACHE_KEY_PREFIX }}-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run ESLint
        run: npm run lint
        env:
          CI: true

      - name: Type check
        run: npm run type-check
        env:
          CI: true

      - name: Run tests with coverage
        run: npm run test
        env:
          CI: true
          NODE_ENV: test
          COVERAGE_THRESHOLD: ${{ env.COVERAGE_THRESHOLD }}

      - name: Build application
        run: npm run build
        env:
          CI: true
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            ${{ env.WORKING_DIRECTORY }}/build
            ${{ env.WORKING_DIRECTORY }}/coverage
          retention-days: 14

      - name: Upload coverage reports
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: ${{ env.WORKING_DIRECTORY }}/coverage
          retention-days: 14

      - name: Check bundle size
        run: |
          if [ -f "build/static/js/main.*.js" ]; then
            echo "Bundle size:"
            ls -lh build/static/js/main.*.js
          fi